---

fits_version: "1.3.0"

fits_base_url: "http://projects.iq.harvard.edu/files/fits/files"

fits_download_file: "fits-{{ fits_version }}.zip"

fits_download_url: "{{ fits_base_url }}/{{ fits_download_file }}"

fits_install_path: "/opt/fits-{{ fits_version }}"

fits_user_path: "/usr/local/bin"
